/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './shared/routes/__root'
import { Route as IndexRouteImport } from './shared/routes/index'
import { Route as HomeIndexRouteImport } from './shared/routes/home/index'
import { Route as GameDetailsGameIdRouteImport } from './shared/routes/game-details/$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameDetailsGameIdRoute = GameDetailsGameIdRouteImport.update({
  id: '/game-details/$gameId',
  path: '/game-details/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game-details/$gameId': typeof GameDetailsGameIdRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game-details/$gameId': typeof GameDetailsGameIdRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game-details/$gameId': typeof GameDetailsGameIdRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game-details/$gameId' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game-details/$gameId' | '/home'
  id: '__root__' | '/' | '/game-details/$gameId' | '/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameDetailsGameIdRoute: typeof GameDetailsGameIdRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-details/$gameId': {
      id: '/game-details/$gameId'
      path: '/game-details/$gameId'
      fullPath: '/game-details/$gameId'
      preLoaderRoute: typeof GameDetailsGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameDetailsGameIdRoute: GameDetailsGameIdRoute,
  HomeIndexRoute: HomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
